### ISSUE TITLE
Feature request: log coloration

### ISSUE THREAD

**Issue by SlimeDog** [MegaNarwhal/BiomeFinder#1]
Please introduce a configuration option to disable formatting codes in log entries. I prefer plain text, no colors or etc. Make the default whatever you feel is most requested, but please give me the option.

**Comment by MegaNarwhal** [comment]
Sorry for the wait, uncolored logging is added with 3ccb31f. Update will be posted on Spigot soon.

**Comment by SlimeDog** [comment]
Thank you.
