### ISSUE TITLE
Feature request: alphabetize bcachebuild list

### ISSUE THREAD

**Issue by SlimeDog** [MegaNarwhal/BiomeFinder#10]
Please consider alphabetic sorting of the output listing from bcachebuild, both at console and -- more importantly -- in the file.

**Comment by MegaNarwhal** [comment]
Biomes in cache files are alphabetized as of dcc81da7450de1349fc814beb0bea64300e07665. Caches will need to be rebuilt for this to take effect.

**Comment by SlimeDog** [comment]
Thank you!

**Comment by SlimeDog** [comment]
Confirmed in BF 1.3.1. Thanks again.
