### ISSUE TITLE
bcachebuild request

### ISSUE THREAD

**Issue by stealthdragon** [MegaNarwhal/BiomeFinder#6]
Since getting to the server console can be a pain even for people like me who have it running in a closet upstairs would it be possible to enable bcachebuild to run from rcon at least since I assume the reason for limiting it to the console is so that you can reduce the risk of force generating a lot of chunks while a lot of people are online slowing everything down

**Comment by MegaNarwhal** [comment]
This is now possible as of 8380e211630aeb3258f2e40bc11f12e33980575b and will be included in the next release.
