### ISSUE TITLE
Biome caches not loaded at start-up

### ISSUE THREAD

**Issue by SlimeDog** [MegaNarwhal/BiomeFinder#9]
Spigot 1.15.1 (Jenkins 2558)
BiomeFinder 1.2.9

Only the cache for world _world_ is loaded at server start-up.

Although the appropriate files exist (for example, _plugins/BiomeFinder/world_xyzzy.yml_), after server restart **/bfind** in that world reports
```
BFinder> This world's biomes have not been indexed yet.
```
Actually, they have been, but BiomeFinder loads before Multiverse-Core. Please add Multiverse-Core and MultiWorld as soft dependencies.

**Comment by MegaNarwhal** [comment]
This should be fixed in 41e131d7d7727dfe8d0f7304d032186edf419da7.

**Comment by SlimeDog** [comment]
Confirmed fixed in BF 1.3.0. Thanks.
